#!/bin/sh
######################################################################
# eeepc-tweaks by F.Hendrikx, (c) 2008
# postinst script
######################################################################
set -e


# add eeepc-tweaks init.d script

if [ -x "/etc/init.d/eeepc-tweaks" ]; then
	update-rc.d eeepc-tweaks start 10 2 3 4 5 . stop 10 0 6 . || exit $?
fi


# add eeepc-tweaks GNOME defaults

if [ -x "/usr/sbin/update-gconf-defaults" ]; then
	/usr/sbin/update-gconf-defaults
fi

exit 0
