#!/bin/sh
######################################################################
# eeepc-tweaks v1.1 by Ferry Hendrikx, (c) 2008
#
# System script that automatically configures your Ubuntu Linux system
# for the Asus Eee PC (although these settings will work for any
# standard PC). The main goal is to reduce wear-and-tear on the SSD
# drive.
#
######################################################################
### BEGIN INIT INFO
# Provides:          eeepc-tweaks
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 6
# Short-Description: Asus Eee PC tweaks
# Description:
### END INIT INFO

set -e

NAME="eeepc-tweaks"
DESC="Asus Eee PC tweaks"

. /lib/lsb/init-functions


do_start() {
	log_action_begin_msg "Starting $NAME"

	# ensure that /var/log/apt exists

	mkdir -p /var/log/apt

	log_action_end_msg $?
}


do_stop () {
	log_action_begin_msg "Stopping $NAME"


	# change /etc/fstab

	DEST='/etc/fstab'

	if [ `grep eeepc-tweaks ${DEST} | wc -l` -eq 0 ]; then

		if [ ! -e "${DEST}.eeepc" ]; then
			cp ${DEST} ${DEST}.eeepc
		fi

		sed 's/relatime/noatime/' < ${DEST} > ${DEST}.tmp
		mv ${DEST}.tmp ${DEST}

		grep -v '/media/cdrom' ${DEST} > ${DEST}.tmp
		mv ${DEST}.tmp ${DEST}

		chown root:root ${DEST}

		echo "# settings added by eeepc-tweaks" >> ${DEST}
		echo "tmpfs		/tmp		tmpfs	defaults,noatime,mode=1777	0 0" >> ${DEST}
		echo "tmpfs		/var/tmp	tmpfs	defaults,noatime,mode=1777	0 0" >> ${DEST}
		echo "tmpfs		/var/log	tmpfs	defaults,noatime,mode=0755	0 0" >> ${DEST}
	fi


	# change /boot/grub/menu.lst

	DEST='/boot/grub/menu.lst'

	if [ `grep 'timeout\s*0' ${DEST} | wc -l` -eq 0 ]; then

		sed 's/^timeout\([ \t]*\)[0-9]*/timeout\10/' < ${DEST} > ${DEST}.tmp
		mv ${DEST}.tmp ${DEST}

		chown root:root ${DEST}

		/usr/sbin/update-grub
	fi


	log_action_end_msg $?
}


case "$1" in
	start)
		do_start
		;;
	restart|reload|force-reload)
		;;
	stop)
		do_stop
		;;
	*)
		echo "Usage: $0 [start|stop|restart|reload|force-reload]" >&2
		exit 3
		;;
esac

:
