#!/bin/sh
######################################################################
# eeepc-tweaks by F.Hendrikx, (c) 2008
# postrm script
######################################################################
set -e


# remove eeepc-tweaks init.d script

update-rc.d -f eeepc-tweaks remove >/dev/null || exit $?


# remove eeepc-tweaks GNOME defaults

if [ -x "/usr/sbin/update-gconf-defaults" ]; then
	/usr/sbin/update-gconf-defaults
fi

exit 0
